"""
Phase 1A unit tests for EGX Fundamental Analyst.

Tests:
  - FinancialCalculator: all 14 core ratios + edge cases
  - StatementStandardizer: common-size, YoY, direction signals
  - SectorConfig: sector classification, alert generation
  - scoring.py: data_confidence, signal_coherence
  - FundamentalAnalysisReport: schema validation

Edge cases covered per plan:
  - Negative equity
  - Zero revenue (ZERO_REVENUE_PERIOD)
  - Undefined P/E (EPS <= 0)
  - Single period (no YoY)
  - ROE/margin sign inconsistency
  - DuPont identity failure
  - Current ratio cross-source divergence
"""
import pytest
from typing import Dict, Optional

from tradingagents.agents.analysts.fundamentals.schemas import FundamentalAnalysisReport
from tradingagents.agents.analysts.fundamentals.financial_calculator import FinancialCalculator
from tradingagents.agents.analysts.fundamentals.statement_standardizer import StatementStandardizer
from tradingagents.agents.analysts.fundamentals.sector_config import SectorConfig, classify_sector
from tradingagents.agents.analysts.fundamentals.scoring import (
    compute_data_confidence,
    determine_financial_health_heuristic,
)


# =============================================================================
# FinancialCalculator tests
# =============================================================================

class TestFinancialCalculatorProfitability:

    def test_roe_normal(self):
        assert FinancialCalculator.roe(100.0, 500.0) == pytest.approx(0.20)

    def test_roe_zero_equity(self):
        assert FinancialCalculator.roe(100.0, 0.0) is None

    def test_roe_negative_equity(self):
        # Negative equity: ROE is computed but sign-reversed. Per the plan:
        # "ROE: negative equity makes ROE sign-reversed — flag in evidence pack."
        # The NEGATIVE_EQUITY_ALERT is generated by sector_config, not by roe().
        # roe() returns the mathematically correct (negative) value; caller flags it.
        result = FinancialCalculator.roe(100.0, -200.0)
        assert result is not None
        assert result < 0  # sign-reversed: positive NI / negative equity = negative ROE

    def test_roe_none_inputs(self):
        assert FinancialCalculator.roe(None, 500.0) is None
        assert FinancialCalculator.roe(100.0, None) is None

    def test_roa_normal(self):
        assert FinancialCalculator.roa(100.0, 1000.0) == pytest.approx(0.10)

    def test_roa_zero_assets(self):
        assert FinancialCalculator.roa(100.0, 0.0) is None

    def test_gross_margin_normal(self):
        assert FinancialCalculator.gross_margin(400.0, 1000.0) == pytest.approx(0.40)

    def test_gross_margin_zero_revenue(self):
        assert FinancialCalculator.gross_margin(400.0, 0.0) is None

    def test_operating_margin(self):
        assert FinancialCalculator.operating_margin(200.0, 1000.0) == pytest.approx(0.20)

    def test_net_margin_negative(self):
        # Negative net income (loss) should return negative margin
        result = FinancialCalculator.net_margin(-50.0, 1000.0)
        assert result == pytest.approx(-0.05)

    def test_net_margin_zero_revenue(self):
        assert FinancialCalculator.net_margin(50.0, 0.0) is None


class TestFinancialCalculatorLeverage:

    def test_debt_to_equity_normal(self):
        assert FinancialCalculator.debt_to_equity(600.0, 400.0) == pytest.approx(1.5)

    def test_debt_to_equity_zero_equity(self):
        assert FinancialCalculator.debt_to_equity(600.0, 0.0) is None

    def test_debt_to_equity_negative_equity(self):
        # Negative equity: D/E undefined per design
        assert FinancialCalculator.debt_to_equity(600.0, -100.0) is None

    def test_current_ratio_normal(self):
        assert FinancialCalculator.current_ratio(300.0, 200.0) == pytest.approx(1.5)

    def test_current_ratio_zero_liabilities(self):
        assert FinancialCalculator.current_ratio(300.0, 0.0) is None


class TestFinancialCalculatorDuPont:

    def test_asset_turnover(self):
        assert FinancialCalculator.asset_turnover(1000.0, 2000.0) == pytest.approx(0.5)

    def test_equity_multiplier(self):
        assert FinancialCalculator.equity_multiplier(1000.0, 400.0) == pytest.approx(2.5)

    def test_dupont_3factor_identity(self):
        # ROE = NM × AT × EM should hold algebraically
        nm = 0.10   # 10% net margin
        at = 0.5    # 0.5× asset turnover
        em = 2.5    # 2.5× equity multiplier
        dp3 = FinancialCalculator.dupont_3factor(nm, at, em)
        assert dp3 == pytest.approx(0.125)   # 10% × 0.5 × 2.5 = 12.5% ROE

    def test_dupont_none_propagation(self):
        assert FinancialCalculator.dupont_3factor(None, 0.5, 2.5) is None


class TestFinancialCalculatorValuation:

    def test_pe_ratio_normal(self):
        assert FinancialCalculator.pe_ratio(100.0, 10.0) == pytest.approx(10.0)

    def test_pe_ratio_negative_eps(self):
        # P/E undefined for negative EPS
        assert FinancialCalculator.pe_ratio(100.0, -5.0) is None

    def test_pe_ratio_zero_eps(self):
        assert FinancialCalculator.pe_ratio(100.0, 0.0) is None

    def test_earnings_yield(self):
        # EY = 1 / PE
        assert FinancialCalculator.earnings_yield(10.0) == pytest.approx(0.10)

    def test_earnings_yield_undefined_pe(self):
        assert FinancialCalculator.earnings_yield(None) is None
        assert FinancialCalculator.earnings_yield(0.0) is None

    def test_pb_ratio(self):
        assert FinancialCalculator.pb_ratio(120.0, 100.0) == pytest.approx(1.2)

    def test_earnings_yield_spread(self):
        ey = 0.20  # 20% earnings yield (PE = 5)
        rf = 0.19  # 19% risk-free rate (CBE corridor ~19.25%)
        spread = FinancialCalculator.earnings_yield_spread(ey, rf)
        assert spread == pytest.approx(0.01)

    def test_earnings_yield_spread_none_risk_free(self):
        assert FinancialCalculator.earnings_yield_spread(0.20, None) is None


class TestSignalCoherence:

    def test_perfect_coherence_no_deductions(self):
        # Consistent data: ROE > 0, NM > 0, DuPont holds
        nm = 0.10
        at = 0.5
        em = 2.5
        roe = nm * at * em  # = 0.125 — DuPont identity holds
        ratios = {
            "roe": roe, "net_margin": nm,
            "asset_turnover": at, "equity_multiplier": em,
            "dupont_3factor": roe,
            "current_ratio": 1.5,
        }
        score, reasons = FinancialCalculator.compute_signal_coherence(ratios)
        assert score == 100
        assert reasons == []

    def test_roe_margin_inconsistency(self):
        # ROE positive but net_margin negative — mathematical impossibility
        ratios = {
            "roe": 0.10, "net_margin": -0.05,
            "asset_turnover": 1.0, "equity_multiplier": 2.0,
            "dupont_3factor": None,
        }
        score, reasons = FinancialCalculator.compute_signal_coherence(ratios)
        assert score == 85  # −15 deduction
        assert any("ROE is positive but net_margin is negative" in r for r in reasons)

    def test_dupont_identity_failure(self):
        # DuPont identity fails: NM × AT × EM ≠ ROE
        nm = 0.10
        at = 0.5
        em = 2.5
        dp3 = nm * at * em  # = 0.125
        roe = 0.20  # Claimed ROE is 20%, but DuPont says 12.5%
        ratios = {
            "roe": roe, "net_margin": nm,
            "asset_turnover": at, "equity_multiplier": em,
            "dupont_3factor": dp3,
        }
        score, reasons = FinancialCalculator.compute_signal_coherence(ratios)
        assert score == 90  # −10 deduction
        assert any("DuPont identity fails" in r for r in reasons)

    def test_current_ratio_cross_source_divergence(self):
        # CSV says 1.5 but balance sheet computes 2.5 (67% divergence)
        ratios = {
            "roe": 0.10, "net_margin": 0.05,
            "current_ratio": 1.5,  # CSV value
        }
        score, reasons = FinancialCalculator.compute_signal_coherence(
            ratios,
            current_ratio_csv=1.5,
            current_assets=500.0,
            current_liabilities=200.0,  # Computes to 2.5 — 67% divergence from 1.5
        )
        assert score == 85  # −15 deduction
        assert any("Current ratio divergence" in r for r in reasons)

    def test_no_coverage_penalty_for_missing_optional_fields(self):
        # P/E and P/B missing should NOT penalize signal_coherence
        ratios = {
            "roe": 0.10, "net_margin": 0.10,
            "asset_turnover": 0.5, "equity_multiplier": 2.0,
            "dupont_3factor": 0.10,  # Matches ROE
            "pe_ratio": None,   # Missing — should NOT penalize
            "pb_ratio": None,   # Missing — should NOT penalize
        }
        score, reasons = FinancialCalculator.compute_signal_coherence(ratios)
        assert score == 100  # No deduction for missing optional coverage


# =============================================================================
# StatementStandardizer tests
# =============================================================================

class TestCommonSize:

    def test_common_size_income(self):
        row = {
            "revenue": 1000.0,
            "gross_profit": 400.0,
            "operating_income": 200.0,
            "net_income": 100.0,
            "cost_of_revenue": 600.0,
        }
        result = StatementStandardizer.common_size_income(row)
        assert result["gross_profit_pct"] == pytest.approx(0.40)
        assert result["net_income_pct"] == pytest.approx(0.10)
        assert result["cost_of_revenue_pct"] == pytest.approx(0.60)

    def test_common_size_income_zero_revenue(self):
        row = {"revenue": 0.0, "gross_profit": 400.0}
        result = StatementStandardizer.common_size_income(row)
        assert result == {}

    def test_common_size_balance(self):
        row = {
            "total_assets": 1000.0,
            "total_liabilities": 600.0,
            "total_equity": 400.0,
            "current_assets": 300.0,
        }
        result = StatementStandardizer.common_size_balance(row)
        assert result["total_liabilities_pct"] == pytest.approx(0.60)
        assert result["total_equity_pct"] == pytest.approx(0.40)
        assert result["current_assets_pct"] == pytest.approx(0.30)
        # total_assets itself should NOT appear as a pct
        assert "total_assets_pct" not in result


class TestYoYChanges:

    def test_yoy_positive_growth(self):
        curr = {"revenue": 1200.0, "net_income": 120.0}
        prior = {"revenue": 1000.0, "net_income": 100.0}
        result = StatementStandardizer.yoy_changes(curr, prior)
        assert result["revenue"]["pct"] == pytest.approx(0.20)
        assert result["revenue"]["absolute"] == pytest.approx(200.0)
        assert result["net_income"]["pct"] == pytest.approx(0.20)

    def test_yoy_zero_prior(self):
        # Prior is zero — pct should be None
        curr = {"revenue": 100.0}
        prior = {"revenue": 0.0}
        result = StatementStandardizer.yoy_changes(curr, prior)
        assert result["revenue"]["pct"] is None
        assert result["revenue"]["absolute"] == pytest.approx(100.0)

    def test_yoy_missing_field(self):
        curr = {"revenue": 1200.0}
        prior = {}
        result = StatementStandardizer.yoy_changes(curr, prior)
        assert result["revenue"]["pct"] is None


class TestDirectionSignals:

    def test_direction_improving(self):
        d = StatementStandardizer.direction(0.15, 0.10)
        assert d == "improving"

    def test_direction_deteriorating(self):
        d = StatementStandardizer.direction(0.08, 0.10)
        assert d == "deteriorating"

    def test_direction_stable(self):
        # Within ±2% threshold
        d = StatementStandardizer.direction(0.101, 0.10)
        assert d == "stable"

    def test_direction_insufficient_history(self):
        d = StatementStandardizer.direction(None, 0.10)
        assert d == "insufficient_history"
        d2 = StatementStandardizer.direction(0.10, None)
        assert d2 == "insufficient_history"

    def test_direction_lower_is_better(self):
        # D/E declining is "improving"
        d = StatementStandardizer.direction(1.0, 2.0, higher_is_better=False)
        assert d == "improving"
        # D/E rising is "deteriorating"
        d2 = StatementStandardizer.direction(3.0, 2.0, higher_is_better=False)
        assert d2 == "deteriorating"


class TestGrowthMetrics:

    def test_revenue_growth_positive(self):
        assert StatementStandardizer.revenue_growth_yoy(1200.0, 1000.0) == pytest.approx(0.20)

    def test_revenue_growth_negative(self):
        assert StatementStandardizer.revenue_growth_yoy(800.0, 1000.0) == pytest.approx(-0.20)

    def test_revenue_growth_zero_prior(self):
        assert StatementStandardizer.revenue_growth_yoy(100.0, 0.0) is None

    def test_revenue_growth_none_inputs(self):
        assert StatementStandardizer.revenue_growth_yoy(None, 1000.0) is None


# =============================================================================
# SectorConfig tests
# =============================================================================

class TestSectorClassification:

    def test_known_bank_tickers(self):
        assert classify_sector("COMI") == "banks"
        assert classify_sector("NBE") == "banks"

    def test_known_real_estate_tickers(self):
        assert classify_sector("OCDI") == "real_estate"
        assert classify_sector("PHD") == "real_estate"

    def test_known_holdings_tickers(self):
        assert classify_sector("HRHO") == "holdings"
        assert classify_sector("SWDY") == "holdings"

    def test_known_operational_tickers(self):
        assert classify_sector("ETEL") == "operational"
        assert classify_sector("SVCE") == "operational"

    def test_unknown_ticker_defaults_to_operational(self):
        assert classify_sector("XXXX") == "operational"

    def test_case_insensitive(self):
        assert classify_sector("comi") == "banks"
        assert classify_sector("Comi") == "banks"


class TestDistressFlagGeneration:

    def test_negative_margin_alert_all_sectors(self):
        """NEGATIVE_MARGIN_ALERT fires on all sectors."""
        for sector_ticker in ["COMI", "OCDI", "HRHO", "ETEL"]:
            cfg = SectorConfig(sector_ticker)
            flags = cfg.generate_distress_flags(
                net_margin=-0.05, debt_to_equity=1.0, current_ratio=1.5,
                total_equity=1000.0, revenue=500.0, eps=5.0, pe_ratio=10.0, roe=0.10,
            )
            assert "NEGATIVE_MARGIN_ALERT" in flags, f"NEGATIVE_MARGIN_ALERT should fire for {sector_ticker}"

    def test_high_leverage_alert_operational_only(self):
        """HIGH_LEVERAGE_ALERT fires only for operational sector."""
        op_cfg = SectorConfig("ETEL")  # operational
        flags = op_cfg.generate_distress_flags(
            net_margin=0.05, debt_to_equity=6.0, current_ratio=1.5,
            total_equity=1000.0, revenue=500.0, eps=5.0, pe_ratio=10.0, roe=0.10,
        )
        assert "HIGH_LEVERAGE_ALERT" in flags

    def test_high_leverage_alert_does_not_fire_for_banks(self):
        """HIGH_LEVERAGE_ALERT must NOT fire for banks with D/E = 8× (structurally normal)."""
        bank_cfg = SectorConfig("COMI")  # banks
        flags = bank_cfg.generate_distress_flags(
            net_margin=0.20, debt_to_equity=8.0, current_ratio=None,
            total_equity=5000.0, revenue=2000.0, eps=10.0, pe_ratio=8.0, roe=0.25,
        )
        assert "HIGH_LEVERAGE_ALERT" not in flags, "HIGH_LEVERAGE_ALERT must not fire for banks"

    def test_liquidity_emergency_operational_only(self):
        """LIQUIDITY_EMERGENCY fires only for operational sector."""
        op_cfg = SectorConfig("ETEL")
        flags = op_cfg.generate_distress_flags(
            net_margin=0.05, debt_to_equity=1.0, current_ratio=0.3,
            total_equity=1000.0, revenue=500.0, eps=5.0, pe_ratio=10.0, roe=0.10,
        )
        assert "LIQUIDITY_EMERGENCY" in flags

    def test_liquidity_emergency_does_not_fire_for_banks(self):
        """LIQUIDITY_EMERGENCY must NOT fire for banks (current_ratio not applicable)."""
        bank_cfg = SectorConfig("COMI")
        flags = bank_cfg.generate_distress_flags(
            net_margin=0.20, debt_to_equity=None, current_ratio=0.1,  # banks don't use current ratio
            total_equity=5000.0, revenue=2000.0, eps=10.0, pe_ratio=8.0, roe=0.25,
        )
        assert "LIQUIDITY_EMERGENCY" not in flags

    def test_pe_undefined_negative_eps(self):
        cfg = SectorConfig("ETEL")
        flags = cfg.generate_distress_flags(
            net_margin=0.05, debt_to_equity=1.0, current_ratio=1.5,
            total_equity=1000.0, revenue=500.0, eps=-5.0, pe_ratio=None, roe=0.10,
        )
        assert "PE_UNDEFINED" in flags

    def test_negative_equity_alert(self):
        cfg = SectorConfig("ETEL")
        flags = cfg.generate_distress_flags(
            net_margin=0.05, debt_to_equity=None, current_ratio=1.5,
            total_equity=-200.0, revenue=500.0, eps=5.0, pe_ratio=10.0, roe=-0.10,
        )
        assert "NEGATIVE_EQUITY_ALERT" in flags

    def test_real_estate_pb_understated_flag(self):
        cfg = SectorConfig("OCDI")  # real_estate
        flags = cfg.generate_distress_flags(
            net_margin=0.10, debt_to_equity=1.5, current_ratio=1.2,
            total_equity=1000.0, revenue=500.0, eps=5.0, pe_ratio=10.0, roe=0.10,
        )
        assert "PB_UNDERSTATED_HISTORICAL_COST" in flags

    def test_holdings_consolidated_blending_flag(self):
        cfg = SectorConfig("HRHO")  # holdings
        flags = cfg.generate_distress_flags(
            net_margin=0.08, debt_to_equity=1.0, current_ratio=1.5,
            total_equity=1000.0, revenue=500.0, eps=5.0, pe_ratio=10.0, roe=0.10,
        )
        assert "CONSOLIDATED_BLENDING" in flags

    def test_no_false_alerts_on_healthy_operational_company(self):
        """A healthy operational company should get no hard distress alerts."""
        cfg = SectorConfig("ETEL")
        flags = cfg.generate_distress_flags(
            net_margin=0.12, debt_to_equity=1.5, current_ratio=2.0,
            total_equity=1000.0, revenue=500.0, eps=8.0, pe_ratio=10.0, roe=0.15,
        )
        hard_alerts = {"NEGATIVE_MARGIN_ALERT", "HIGH_LEVERAGE_ALERT", "LIQUIDITY_EMERGENCY", "NEGATIVE_EQUITY_ALERT", "ZERO_REVENUE_PERIOD"}
        assert not (hard_alerts & set(flags)), f"Unexpected hard alerts on healthy company: {set(flags) & hard_alerts}"

    def test_zero_revenue_period(self):
        cfg = SectorConfig("ETEL")
        flags = cfg.generate_distress_flags(
            net_margin=None, debt_to_equity=1.0, current_ratio=1.5,
            total_equity=1000.0, revenue=0.0, eps=None, pe_ratio=None, roe=None,
        )
        assert "ZERO_REVENUE_PERIOD" in flags

    def test_roe_margin_inconsistency_flag(self):
        cfg = SectorConfig("ETEL")
        flags = cfg.generate_distress_flags(
            net_margin=-0.05, debt_to_equity=1.0, current_ratio=1.5,
            total_equity=1000.0, revenue=500.0, eps=5.0, pe_ratio=None, roe=0.10,
        )
        assert "ROE_MARGIN_INCONSISTENCY" in flags


# =============================================================================
# Scoring tests
# =============================================================================

class TestDataConfidence:

    def _full_income(self):
        return {
            "revenue": 1000.0, "gross_profit": 400.0,
            "operating_income": 200.0, "net_income": 100.0,
            "cost_of_revenue": 600.0, "ebitda": 220.0, "eps_basic": 5.0,
        }

    def _full_balance(self):
        return {
            "total_assets": 2000.0, "total_liabilities": 1200.0, "total_equity": 800.0,
            "cash_and_equivalents": 200.0, "current_assets": 500.0,
            "current_liabilities": 300.0, "long_term_debt": 500.0,
            "shares_outstanding": 20.0,
        }

    def _full_ratios(self):
        return {
            "pe_ratio": 10.0, "eps": 5.0, "debt_to_equity": 1.5,
            "current_ratio": 1.67, "roe": 0.125, "roa": 0.05,
            "gross_margin": 0.40, "net_margin": 0.10,
            "book_value_per_share": 40.0,
        }

    def test_full_data_high_confidence(self):
        score = compute_data_confidence(
            income_row=self._full_income(),
            balance_row=self._full_balance(),
            ratios_row=self._full_ratios(),
            n_annual_periods=5,
            periods_since_last_filing=0,
        )
        assert score > 80, f"Full data should yield > 80, got {score}"

    def test_partial_data_low_confidence(self):
        # Only income statement (4 of 7 required fields), no balance or ratios.
        # With field_coverage = 4/7 ≈ 0.57 and full staleness, formula gives ~54.
        # Key check: partial data confidence should be materially lower than full data (> 80).
        score = compute_data_confidence(
            income_row={"revenue": 1000.0, "gross_profit": 400.0,
                        "operating_income": 200.0, "net_income": 100.0},
            balance_row={},  # No balance sheet — 3 required fields missing
            ratios_row={},   # No ratios
            n_annual_periods=2,
            periods_since_last_filing=0,
        )
        assert score < 65, f"Partial data (no balance) should yield < 65, got {score}"
        # Also verify it is lower than the full-data score tested in test_full_data_high_confidence
        assert score < 80, f"Partial data should be < full data threshold (80), got {score}"

    def test_distress_does_not_lower_confidence(self):
        """A company with negative net income but complete data should have high data_confidence."""
        distressed_income = {
            "revenue": 1000.0, "gross_profit": 400.0,
            "operating_income": -50.0, "net_income": -100.0,
        }
        score = compute_data_confidence(
            income_row=distressed_income,
            balance_row=self._full_balance(),
            ratios_row={},
            n_annual_periods=3,
            periods_since_last_filing=0,
        )
        healthy_income = {
            "revenue": 1000.0, "gross_profit": 400.0,
            "operating_income": 200.0, "net_income": 100.0,
        }
        score_healthy = compute_data_confidence(
            income_row=healthy_income,
            balance_row=self._full_balance(),
            ratios_row={},
            n_annual_periods=3,
            periods_since_last_filing=0,
        )
        # Both should have same score — distress doesn't penalize
        assert score == score_healthy, (
            f"Distressed company data_confidence ({score}) should equal "
            f"healthy company data_confidence ({score_healthy}) when data is equally complete"
        )

    def test_stale_data_lower_confidence(self):
        # 5 periods since filing — very stale
        score_stale = compute_data_confidence(
            income_row=self._full_income(),
            balance_row=self._full_balance(),
            ratios_row=self._full_ratios(),
            n_annual_periods=5,
            periods_since_last_filing=5,
        )
        score_fresh = compute_data_confidence(
            income_row=self._full_income(),
            balance_row=self._full_balance(),
            ratios_row=self._full_ratios(),
            n_annual_periods=5,
            periods_since_last_filing=0,
        )
        assert score_stale < score_fresh, "Stale data should have lower confidence than fresh data"


class TestFinancialHealthHeuristic:

    def test_all_improving_is_healthy(self):
        directions = {
            "net_margin": "improving", "operating_margin": "improving",
            "roe": "improving", "roa": "improving",
            "debt_to_equity": "improving", "total_liabilities": "improving",
        }
        assert determine_financial_health_heuristic(directions) == "healthy"

    def test_all_deteriorating_is_critical(self):
        directions = {
            "net_margin": "deteriorating", "operating_margin": "deteriorating",
            "roe": "deteriorating", "roa": "deteriorating",
            "debt_to_equity": "deteriorating", "total_liabilities": "deteriorating",
        }
        assert determine_financial_health_heuristic(directions) == "critical"

    def test_mixed_is_concerning(self):
        directions = {
            "net_margin": "improving", "operating_margin": "stable",
            "roe": "deteriorating", "roa": "deteriorating",
            "debt_to_equity": "improving", "total_liabilities": "stable",
        }
        result = determine_financial_health_heuristic(directions)
        # ~2/6 deteriorating = 33% — should be "concerning"
        assert result in ("concerning", "healthy")  # boundary case

    def test_insufficient_history(self):
        # All insufficient_history → insufficient_data
        directions = {k: "insufficient_history" for k in
                      ["net_margin", "operating_margin", "roe", "roa", "debt_to_equity"]}
        assert determine_financial_health_heuristic(directions) == "insufficient_data"

    def test_negative_equity_roe_does_not_contaminate_verdict(self):
        """
        When equity is negative in both periods, ROE direction is sign-reversed
        and appears 'improving' even though the company is distressed.
        The analyst must nullify ROE before calling the heuristic.
        Verify that the correct (pre-patched) directions do not produce a 'healthy'
        verdict when the actual situation is deteriorating.
        """
        # Simulate: ROE contaminated (sign-reversed looks 'improving')
        contaminated_directions = {
            'net_margin': 'deteriorating',
            'operating_margin': 'stable',
            'roe': 'improving',          # sign-reversed artifact
            'roa': 'deteriorating',
            'debt_to_equity': 'stable',
            'total_liabilities': 'stable',
        }
        # This would produce 'healthy' — the wrong verdict
        uncleaned = determine_financial_health_heuristic(contaminated_directions)
        assert uncleaned == 'healthy'  # documenting the broken state

        # After nullifying ROE (as the analyst does when NEGATIVE_EQUITY_ALERT fires)
        cleaned_directions = {**contaminated_directions, 'roe': 'insufficient_history'}
        cleaned = determine_financial_health_heuristic(cleaned_directions)
        assert cleaned == 'concerning'  # correct verdict without contamination
        assert cleaned != uncleaned, "Nullifying sign-reversed ROE must change the verdict"


# =============================================================================
# FundamentalAnalysisReport schema tests
# =============================================================================

class TestFundamentalAnalysisReportSchema:

    def test_default_instantiation(self):
        r = FundamentalAnalysisReport(
            ticker="COMI",
            analysis_date="2024-01-01",
            fiscal_period="FY2023",
            sector="banks",
        )
        assert r.ticker == "COMI"
        assert r.sector == "banks"
        assert r.data_confidence == 0
        assert r.signal_coherence == 100
        assert r.distress_flags == []
        assert r.pipeline_mode == "deterministic"

    def test_three_scores_are_independent(self):
        """signal_coherence and distress_flags are conceptually independent."""
        r = FundamentalAnalysisReport(
            ticker="ETEL",
            analysis_date="2024-01-01",
            fiscal_period="FY2023",
            sector="operational",
            data_confidence=85,
            signal_coherence=100,  # No math inconsistency
            distress_flags=["NEGATIVE_MARGIN_ALERT"],  # Business distress
        )
        # Distress flag does NOT lower signal_coherence
        assert r.signal_coherence == 100
        assert "NEGATIVE_MARGIN_ALERT" in r.distress_flags

    def test_bounds_enforcement(self):
        """Pydantic should reject scores outside 0–100."""
        with pytest.raises(Exception):
            FundamentalAnalysisReport(
                ticker="TEST", analysis_date="2024-01-01",
                fiscal_period="FY2023", sector="operational",
                data_confidence=150,  # Invalid
            )
        with pytest.raises(Exception):
            FundamentalAnalysisReport(
                ticker="TEST", analysis_date="2024-01-01",
                fiscal_period="FY2023", sector="operational",
                signal_coherence=-5,  # Invalid
            )

    def test_full_report_serialization(self):
        r = FundamentalAnalysisReport(
            ticker="COMI",
            analysis_date="2024-01-01",
            fiscal_period="FY2023",
            sector="banks",
            ratios={"roe": 0.15, "net_margin": 0.20, "pe_ratio": None},
            distress_flags=["CONSOLIDATED_BLENDING"],
            data_confidence=82,
            signal_coherence=90,
            financial_health="healthy",
            earnings_direction="up",
            earnings_direction_confidence=65,
            key_risks=["EGX market structure risk"],
            pipeline_mode="cot_full",
            stages_completed=["data_cot", "concept_cot", "thesis_cot"],
        )
        dumped = r.model_dump()
        assert dumped["ticker"] == "COMI"
        assert dumped["ratios"]["roe"] == 0.15
        assert dumped["ratios"]["pe_ratio"] is None
        assert dumped["data_confidence"] == 82
        assert dumped["signal_coherence"] == 90
        assert "CONSOLIDATED_BLENDING" in dumped["distress_flags"]
