/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRunRouteImport } from './routes/_authenticated/run'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedBacktestRouteImport } from './routes/_authenticated/backtest'
import { Route as AuthenticatedHistoryIndexRouteImport } from './routes/_authenticated/history.index'
import { Route as AuthenticatedBacktestIndexRouteImport } from './routes/_authenticated/backtest.index'
import { Route as AuthenticatedHistoryIdRouteImport } from './routes/_authenticated/history.$id'
import { Route as AuthenticatedBacktestIdRouteImport } from './routes/_authenticated/backtest.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRunRoute = AuthenticatedRunRouteImport.update({
  id: '/run',
  path: '/run',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBacktestRoute = AuthenticatedBacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoryIndexRoute =
  AuthenticatedHistoryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedHistoryRoute,
  } as any)
const AuthenticatedBacktestIndexRoute =
  AuthenticatedBacktestIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBacktestRoute,
  } as any)
const AuthenticatedHistoryIdRoute = AuthenticatedHistoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedHistoryRoute,
} as any)
const AuthenticatedBacktestIdRoute = AuthenticatedBacktestIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedBacktestRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/backtest': typeof AuthenticatedBacktestRouteWithChildren
  '/history': typeof AuthenticatedHistoryRouteWithChildren
  '/run': typeof AuthenticatedRunRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/backtest/$id': typeof AuthenticatedBacktestIdRoute
  '/history/$id': typeof AuthenticatedHistoryIdRoute
  '/backtest/': typeof AuthenticatedBacktestIndexRoute
  '/history/': typeof AuthenticatedHistoryIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/run': typeof AuthenticatedRunRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/backtest/$id': typeof AuthenticatedBacktestIdRoute
  '/history/$id': typeof AuthenticatedHistoryIdRoute
  '/backtest': typeof AuthenticatedBacktestIndexRoute
  '/history': typeof AuthenticatedHistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/backtest': typeof AuthenticatedBacktestRouteWithChildren
  '/_authenticated/history': typeof AuthenticatedHistoryRouteWithChildren
  '/_authenticated/run': typeof AuthenticatedRunRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/backtest/$id': typeof AuthenticatedBacktestIdRoute
  '/_authenticated/history/$id': typeof AuthenticatedHistoryIdRoute
  '/_authenticated/backtest/': typeof AuthenticatedBacktestIndexRoute
  '/_authenticated/history/': typeof AuthenticatedHistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/backtest'
    | '/history'
    | '/run'
    | '/settings'
    | '/backtest/$id'
    | '/history/$id'
    | '/backtest/'
    | '/history/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/run'
    | '/settings'
    | '/'
    | '/backtest/$id'
    | '/history/$id'
    | '/backtest'
    | '/history'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/backtest'
    | '/_authenticated/history'
    | '/_authenticated/run'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/backtest/$id'
    | '/_authenticated/history/$id'
    | '/_authenticated/backtest/'
    | '/_authenticated/history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/run': {
      id: '/_authenticated/run'
      path: '/run'
      fullPath: '/run'
      preLoaderRoute: typeof AuthenticatedRunRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/backtest': {
      id: '/_authenticated/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof AuthenticatedBacktestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history/': {
      id: '/_authenticated/history/'
      path: '/'
      fullPath: '/history/'
      preLoaderRoute: typeof AuthenticatedHistoryIndexRouteImport
      parentRoute: typeof AuthenticatedHistoryRoute
    }
    '/_authenticated/backtest/': {
      id: '/_authenticated/backtest/'
      path: '/'
      fullPath: '/backtest/'
      preLoaderRoute: typeof AuthenticatedBacktestIndexRouteImport
      parentRoute: typeof AuthenticatedBacktestRoute
    }
    '/_authenticated/history/$id': {
      id: '/_authenticated/history/$id'
      path: '/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof AuthenticatedHistoryIdRouteImport
      parentRoute: typeof AuthenticatedHistoryRoute
    }
    '/_authenticated/backtest/$id': {
      id: '/_authenticated/backtest/$id'
      path: '/$id'
      fullPath: '/backtest/$id'
      preLoaderRoute: typeof AuthenticatedBacktestIdRouteImport
      parentRoute: typeof AuthenticatedBacktestRoute
    }
  }
}

interface AuthenticatedBacktestRouteChildren {
  AuthenticatedBacktestIdRoute: typeof AuthenticatedBacktestIdRoute
  AuthenticatedBacktestIndexRoute: typeof AuthenticatedBacktestIndexRoute
}

const AuthenticatedBacktestRouteChildren: AuthenticatedBacktestRouteChildren = {
  AuthenticatedBacktestIdRoute: AuthenticatedBacktestIdRoute,
  AuthenticatedBacktestIndexRoute: AuthenticatedBacktestIndexRoute,
}

const AuthenticatedBacktestRouteWithChildren =
  AuthenticatedBacktestRoute._addFileChildren(
    AuthenticatedBacktestRouteChildren,
  )

interface AuthenticatedHistoryRouteChildren {
  AuthenticatedHistoryIdRoute: typeof AuthenticatedHistoryIdRoute
  AuthenticatedHistoryIndexRoute: typeof AuthenticatedHistoryIndexRoute
}

const AuthenticatedHistoryRouteChildren: AuthenticatedHistoryRouteChildren = {
  AuthenticatedHistoryIdRoute: AuthenticatedHistoryIdRoute,
  AuthenticatedHistoryIndexRoute: AuthenticatedHistoryIndexRoute,
}

const AuthenticatedHistoryRouteWithChildren =
  AuthenticatedHistoryRoute._addFileChildren(AuthenticatedHistoryRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedBacktestRoute: typeof AuthenticatedBacktestRouteWithChildren
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRouteWithChildren
  AuthenticatedRunRoute: typeof AuthenticatedRunRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBacktestRoute: AuthenticatedBacktestRouteWithChildren,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRouteWithChildren,
  AuthenticatedRunRoute: AuthenticatedRunRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
