from typing import Annotated, Dict, List, Optional, Sequence
from datetime import date, timedelta, datetime
from typing_extensions import TypedDict
from langchain_openai import ChatOpenAI
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages
from tradingagents.agents import *
from langgraph.prebuilt import ToolNode
from langgraph.graph import END, StateGraph, START, MessagesState


def _keep_last(a, b):
    """Reducer that keeps the latest value — allows sequential (and concurrent) writes."""
    return b


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length
    # Structured JSON theses produced by Bull/Bear researchers (Phase 2d/2e)
    bull_thesis: Annotated[Optional[Dict], "Structured bullish thesis JSON"]
    bear_thesis: Annotated[Optional[Dict], "Structured bearish thesis JSON"]



# Risk management team state
class RiskDebateState(TypedDict):
    risky_history: Annotated[
        str, "Risky Agent's Conversation history"
    ]  # Conversation history
    safe_history: Annotated[
        str, "Safe Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_risky_response: Annotated[
        str, "Latest response by the risky analyst"
    ]  # Last response
    current_safe_response: Annotated[
        str, "Latest response by the safe analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, _keep_last]

    # Per-analyst isolated message channels for parallel execution.
    # Each analyst reads/writes only its own channel so they don't interfere
    # when running in the same LangGraph super-step.
    market_messages:       Annotated[List[BaseMessage], add_messages]
    social_messages:       Annotated[List[BaseMessage], add_messages]
    news_messages:         Annotated[List[BaseMessage], add_messages]
    fundamentals_messages: Annotated[List[BaseMessage], add_messages]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Social Media Analyst"]
    social_sentiment_analysis: Annotated[str, "Structured social media sentiment analysis JSON"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, _keep_last
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, _keep_last
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]

    # EGX-specific fields — all use _keep_last so concurrent/sequential writes
    # from multiple nodes don't raise InvalidUpdateError.
    data_quality: Annotated[Optional[Dict], _keep_last]
    confidence_scores: Annotated[Optional[Dict], _keep_last]
    technical_analysis: Annotated[Optional[Dict], _keep_last]
    fundamental_analysis: Annotated[Optional[Dict], _keep_last]
    sentiment_analysis: Annotated[Optional[Dict], _keep_last]

    # Portfolio context injected by BacktestingEngine
    portfolio_value: Annotated[Optional[float], _keep_last]
    current_price: Annotated[Optional[float], _keep_last]
    avg_daily_volume: Annotated[Optional[float], _keep_last]
    low_liquidity: Annotated[Optional[bool], _keep_last]
    volume_missing: Annotated[Optional[bool], _keep_last]
    current_position: Annotated[Optional[Dict], _keep_last]

    # Execution plan from Trader agent (also updated by Risk Scorer on THROTTLE)
    execution_plan: Annotated[Optional[Dict], _keep_last]

    # Risk assessment from Risk Manager (also seeded by Risk Scorer)
    risk_assessment: Annotated[Optional[Dict], _keep_last]
    risk_veto: Annotated[Optional[bool], _keep_last]

    # Risk Scorer outputs (populated before LLM debate)
    risk_action: Annotated[Optional[str], _keep_last]
    risk_metrics: Annotated[Optional[Dict], _keep_last]

    # Phase 2a: Pre-fetched data (populated by DataPrefetcher before graph starts)
    prefetched_company_news: Annotated[Optional[str], _keep_last]
    prefetched_market_news: Annotated[Optional[str], _keep_last]
    prefetched_social_sentiment: Annotated[Optional[str], _keep_last]
    prefetched_social_posts: Annotated[Optional[str], _keep_last]
    # Phase 3 (PR 5): Layer C StockSentiment pre-LLM gate data.
    prefetched_stock_datapoints: Annotated[Optional[List[Dict]], _keep_last]

    # Phase 3 (PR 7): Layer E sentiment blend result.
    sentiment_blend_result: Annotated[Optional[Dict], _keep_last]

    # EGX-specific market context
    target_market: Annotated[Optional[str], _keep_last]
    trading_currency: Annotated[Optional[str], _keep_last]

    # Macro environment context (populated by DataPrefetcher / get_egx_macro_context)
    # Injected before graph runs; consumed by Research Manager and Risk Manager prompts.
    macro_context: Annotated[Optional[Dict], _keep_last]
