from typing import Annotated, Any, Dict, List, Optional, Sequence
from datetime import date, timedelta, datetime
from typing_extensions import TypedDict
from langchain_openai import ChatOpenAI
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages
from tradingagents.agents import *
from langgraph.prebuilt import ToolNode
from langgraph.graph import END, StateGraph, START, MessagesState


def _keep_last(a, b):
    """Reducer that keeps the latest value — allows sequential (and concurrent) writes."""
    return b


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length
    # Structured JSON theses produced by Bull/Bear researchers (Phase 2d/2e)
    bull_thesis: Annotated[Optional[Dict], "Structured bullish thesis JSON"]
    bear_thesis: Annotated[Optional[Dict], "Structured bearish thesis JSON"]



# Risk management team state
class RiskDebateState(TypedDict):
    risky_history: Annotated[
        str, "Risky Agent's Conversation history"
    ]  # Conversation history
    safe_history: Annotated[
        str, "Safe Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_risky_response: Annotated[
        str, "Latest response by the risky analyst"
    ]  # Last response
    current_safe_response: Annotated[
        str, "Latest response by the safe analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # Per-analyst isolated message channels for parallel execution.
    # Each analyst reads/writes only its own channel so they don't interfere
    # when running in the same LangGraph super-step.
    market_messages:       Annotated[List[BaseMessage], add_messages]
    social_messages:       Annotated[List[BaseMessage], add_messages]
    news_messages:         Annotated[List[BaseMessage], add_messages]
    fundamentals_messages: Annotated[List[BaseMessage], add_messages]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Social Media Analyst"]
    social_sentiment_analysis: Annotated[str, "Structured social media sentiment analysis JSON"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, _keep_last
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, _keep_last
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]

    # EGX-specific fields (must be declared here so LangGraph tracks them across node transitions)
    data_quality: Annotated[Optional[Dict], "Data quality indicators for EGX analysis"]
    confidence_scores: Annotated[Optional[Dict], "Per-analyst confidence scores"]
    technical_analysis: Annotated[Optional[Dict], "Structured output from Market/Technical Analyst"]
    fundamental_analysis: Annotated[Optional[Dict], "Structured output from Fundamentals Analyst"]
    sentiment_analysis: Annotated[Optional[Dict], "Structured output from News Analyst"]

    # Portfolio context injected by BacktestingEngine
    portfolio_value: Annotated[Optional[float], "Current portfolio value in EGP"]
    current_price: Annotated[Optional[float], "Current stock price"]
    avg_daily_volume: Annotated[Optional[float], "Average daily trading volume"]
    low_liquidity: Annotated[Optional[bool], "True if stock has low liquidity"]
    volume_missing: Annotated[Optional[bool], "True if volume data is unavailable"]
    current_position: Annotated[Optional[Dict], "Current holding: {shares, avg_cost, market_value} or empty dict if no position"]

    # Execution plan: written by Trader, then re-written by Risk Scorer
    # (which mutates position_sizing / exit_logic in place). Both writers
    # are sequential by graph topology, but LangGraph still treats writes
    # to the same key in the same super-step as INVALID_CONCURRENT_GRAPH_UPDATE
    # unless a reducer is declared. `_keep_last` makes the resolution explicit.
    execution_plan: Annotated[Optional[Dict], _keep_last]

    # Risk assessment: written by Risk Scorer (deterministic checks) and then
    # again by Risk Judge (LLM-augmented). Same reasoning — declare a reducer.
    risk_assessment: Annotated[Optional[Dict], _keep_last]
    risk_veto: Annotated[Optional[bool], _keep_last]

    # Risk Scorer outputs (populated by Deterministic Risk Scorer node, before LLM debate)
    risk_action: Annotated[Optional[str], "Risk action: ALLOW | WARN | THROTTLE | VETO"]
    risk_metrics: Annotated[Optional[Dict], "Computed risk metrics: position_pct, adv_participation_pct, days_to_exit, per_trade_loss_pct, stop_distance_pct, atr_14"]

    # Phase 2a: Pre-fetched data (populated by DataPrefetcher before graph starts)
    # Eliminates tool-calling round-trips for News and Social analysts
    prefetched_company_news: Annotated[Optional[str], "Pre-fetched company news (bypasses News tool call)"]
    prefetched_market_news: Annotated[Optional[str], "Pre-fetched market news (bypasses News tool call)"]
    prefetched_social_sentiment: Annotated[Optional[str], "Pre-fetched social sentiment scores"]
    prefetched_social_posts: Annotated[Optional[str], "Pre-fetched social media posts"]
    # Phase 3 (PR 5): Layer C StockSentiment pre-LLM gate data.
    # List of dicts matching StockDataPoint fields; populated by prefetcher or
    # external callers. When present and non-empty, social_media_analyst runs
    # compute_stock_sentiment before invoking the LLM and short-circuits on
    # NO_SIGNAL, returning the template "Social sentiment: insufficient data — excluded."
    prefetched_stock_datapoints: Annotated[Optional[List[Dict]], "Pre-built Layer C StockDataPoints for the pre-LLM gate (list of dicts with StockDataPoint fields)"]

    # Phase 3 (PR 7): Layer E sentiment blend result.
    # Dict with keys: confidence_multiplier (float), position_size_multiplier (float),
    # audit (str). Written by social_media_analyst after running blend_sentiment().
    # Read by propagate_confidence() and calculate_unified_score() to apply
    # sentiment-derived multipliers WITHOUT changing directional score.
    sentiment_blend_result: Annotated[Optional[Dict], "Layer E blend output: {confidence_multiplier, position_size_multiplier, audit}"]

    # Manifest-based fundamentals freshness pre-flight (Phase 2C)
    fundamentals_manifest_fresh: Annotated[Optional[bool], "Whether the manifest freshness check passed"]
    fundamentals_manifest_reasons: Annotated[Optional[List[str]], "Freshness failure reasons (empty if fresh)"]
    fundamentals_manifest_checked_tickers: Annotated[Optional[List[str]], "Tickers evaluated by the freshness check"]

    # EGX-specific market context
    target_market: Annotated[Optional[str], "Target market identifier (e.g. 'EGX')"]
    trading_currency: Annotated[Optional[str], "Trading currency (e.g. 'EGP')"]

    # Macro environment context (populated by DataPrefetcher / get_egx_macro_context)
    # Injected before graph runs; consumed by Research Manager, Risk Manager, Trader prompts.
    macro_context: Annotated[Optional[Dict], _keep_last]

    # Market breadth context (Fix C, P8) — populated by prefetcher when enabled
    market_breadth: Annotated[Optional[Dict], _keep_last]

    # Investor context — runtime snapshot of investor profile (profile_id,
    # risk_tolerance, horizon, capital, position limits, sector prefs/exclusions).
    # Injected by TradingAgentsGraph.propagate() when a profile_id is provided.
    # Consumed by Research Manager, Trader, and Risk Manager prompts.
    investor_context: Annotated[Optional[Dict], _keep_last]

    # Anti-churn context (Fix A, P8) — populated by backtester from audit history
    previous_decision: Annotated[Optional[str], "Previous BUY/SELL/HOLD for this ticker"]
    previous_decision_date: Annotated[Optional[str], "Date of previous decision for this ticker"]

    # Node-level audit recorder (infrastructure — not visible to agents).
    # Injected by TradingAgentsGraph.propagate() when backtest_record_outputs
    # is enabled.  Agents call get_recorder(state) to access it.
    _node_recorder: Annotated[Optional[Any], "NodeRecorder instance for audit recording"]
